ALTER TABLE public.schedule_items
  ADD COLUMN IF NOT EXISTS has_sub_slots BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sub_slots JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'general';