ALTER TABLE public.shifts
  ADD COLUMN IF NOT EXISTS shift_category TEXT NOT NULL DEFAULT 'short',
  ADD COLUMN IF NOT EXISTS assigned_teams INT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS train_coupes_published BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS travel_start_date DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS hotel_start_date DATE DEFAULT NULL;